// src/lib/cars.ts

export const cars = [
  {
    id: 1,
    name: "Lamborghini Aventador",
    brand: "Lamborghini",
    price: 800000,
    image: "/cars/lambo.jpg",
    deliveryCharge: 5000,
    description: "A powerful V12 supercar with aggressive styling and extreme performance.",
    features: ["V12 Engine", "Top Speed 350 km/h", "Luxury Interior"],
  },
  {
    id: 2,
    name: "Ferrari SF90",
    brand: "Ferrari",
    price: 950000,
    image: "/cars/ferrari.jpg",
    deliveryCharge: 6000,
    description: "Hybrid supercar combining electric power with Ferrari performance.",
    features: ["Hybrid Engine", "0-100 in 2.5s", "Advanced Aerodynamics"],
  },
  {
    id: 3,
    name: "Rolls Royce Phantom",
    brand: "Rolls Royce",
    price: 1200000,
    image: "/cars/rolls.jpg",
    deliveryCharge: 7000,
    description: "Ultimate luxury sedan with unmatched comfort and elegance.",
    features: ["Handcrafted Interior", "Silent Ride", "Premium Leather"],
  },
  {
    id: 4,
    name: "Bugatti Chiron",
    brand: "Bugatti",
    price: 2000000,
    image: "/cars/bugatti.jpg",
    deliveryCharge: 10000,
    description: "One of the fastest cars in the world with extreme engineering.",
    features: ["W16 Engine", "Top Speed 420 km/h", "Extreme Performance"],
  },
  {
    id: 5,
    name: "BMW i8",
    brand: "BMW",
    price: 300000,
    image: "/cars/bmw.jpg",
    deliveryCharge: 3000,
    description: "Futuristic hybrid sports car with eco-friendly performance.",
    features: ["Hybrid Technology", "Modern Design", "Efficient Engine"],
  },
  {
    id: 6,
    name: "Audi R8",
    brand: "Audi",
    price: 400000,
    image: "/cars/audi.jpg",
    deliveryCharge: 3500,
    description: "Everyday supercar with comfort and high performance.",
    features: ["V10 Engine", "Quattro AWD", "Premium Technology"],
  },
  {
    id: 7,
    name: "Mercedes AMG GT",
    brand: "Mercedes",
    price: 450000,
    image: "/cars/mercedes.jpg",
    deliveryCharge: 4000,
    description: "Luxury performance coupe with sporty design.",
    features: ["AMG Engine", "Sport Mode", "Luxury Interior"],
  },
  {
    id: 8,
    name: "Porsche 911",
    brand: "Porsche",
    price: 500000,
    image: "/cars/porsche.jpg",
    deliveryCharge: 4500,
    description: "Iconic sports car known for precision and design.",
    features: ["Rear Engine", "Precision Handling", "Classic Design"],
  },
  {
    id: 9,
    name: "Tesla Model S Plaid",
    brand: "Tesla",
    price: 600000,
    image: "/cars/tesla.jpg",
    deliveryCharge: 2000,
    description: "High-performance electric car with insane acceleration.",
    features: ["Electric Power", "Autopilot", "0-100 in 2 seconds"],
  },
  {
    id: 10,
    name: "McLaren 720S",
    brand: "McLaren",
    price: 850000,
    image: "/cars/mclaren.jpg",
    deliveryCharge: 5500,
    description: "Lightweight supercar built for track performance.",
    features: ["Carbon Fiber Body", "Twin Turbo Engine", "Track Ready"],
  },
];